name: unfiltrd
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"