name: unfiltrd
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

      # Includes an icon in the footer for each user name you enter
footer-links:
  github: barryclark
  twitter: baznyc
